MoneyTransactions/MoneyTransactions.Web/Controllers/DauTuController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MoneyTransactions.WEB.Controllers
{
    public class DauTuController : Controller
    {
        [HttpGet]
        public ActionResult DienDan()
        {
            return View();
        }

        [HttpGet]
        public ActionResult Article1()
        {
            return View();
        }

        [HttpGet]
        public ActionResult Article2()
        {
            return View();
        }

        [HttpGet]
        public ActionResult Article3()
        {
            return View();
        }

        [HttpGet]
        public ActionResult Article4()
        {
            return View();
        }

        [HttpGet]
        public ActionResult Article5()
        {
            return View();
        }

        // GET: DauTu/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: DauTu/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: DauTu/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: DauTu/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: DauTu/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: DauTu/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: DauTu/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

MoneyTransactions/MoneyTransactions.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>

    <div class="navbar navbar-inverse navbar-fixed-top" id="fix-color">
        <div class="container">
            <div class="navbar-header">
                @Html.ActionLink("Demo", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>

            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav remi-header-top-menu">
                    <li>
                        @if (Session["AccountLogged"] != null)
                        {
                            var getAccount = new MoneyTransactions.BUS.Services.AccountService();
                            var isAdmin = getAccount.FindUserByUserName(Session["AccountLogged"].ToString());
                            if (isAdmin.Role.RoleName.ToLower() == MoneyTransactions.Common.AccountConstant.AdminRole.ToLower())
                            {
                                @Html.ActionLink("Admin", "Admin", "Account")
                            }
                        }
                    </li>
                    <li>@Html.ActionLink("Giao dịch P2P", "Index", "Home")</li>                    
                    <li>
                        @{
                            if (Session["AccountLogged"] != null)
                            {
                                @Html.ActionLink("Diễn dàn", "DienDan", "DauTu")
                            }
                        }
                    </li>
                    <li>
                        @{
                            if (Session["AccountLogged"] == null)
                            {
                                @Html.ActionLink("Diễn dàn", "DienDan", "DauTu")
                            }
                            else
                            {
                                @Html.ActionLink("Ví", "YourWallet", "Home")
                            }
                        }
                    </li>
                    @{ if (Session["AccountLogged"] == null)
                        {
                            <li>
                                @Html.ActionLink("Đăng nhập / Đăng ký", "Login", "Account")
                            </li>
                        }
                        else
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
                                   aria-haspopup="true" aria-expanded="false">
                                    @Session["AccountLogged"].ToString()
                                    <span class="caret"></span>
                                </a>
                                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <li>
                                        @*<a class="dropdown-item" href="">My profile</a>*@
                                        @Html.ActionLink("Hồ sơ", "MyProfile", "Home", null, new { @class = "dropdown-item" })
                                    </li>
                                    <li>
                                        @*<a class="dropdown-item" href="#">Setting</a>*@
                                        @Html.ActionLink("Cài đặt", "Setting", "Home", null, new { @class = "dropdown-item" })
                                    </li>
                                    <li>@Html.ActionLink("Đăng xuất", "Logout", "Account", null, new { @class = "dropdown-item" })</li>
                                </ul>
                            </li>
                        }
                    }
                </ul>
            </div>
        </div>
    </div>

    <!-- From here container from index.cshtml -->
    <!-- Container -->
    @*<div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="alert alert-info" id="div-intro">
                        <p>
                            In order to further protect sellers from fraud attempt,
                            starting Oct 18 2019, Remitano will start apply a withdrawal limit on all account,
                            and increase the limit on a daily basis for each account based on verification level.
                            Please beware of this when you schedule to buy a large amount of coin on Demo.
                        </p>
                    </div>
                </div>
            </div>
        </div>*@

    <div style="padding-bottom:50px;">
        @RenderBody()


        <footer id="footer" class="remi-footer col-xs-12 container forfixedbody">
            <div class="container">
                <div class="col-md-3 col-xs-12">
                    <div class="remi-logo-container">
                        <div class="remi-logo-container remi-logo-img">
                            <img src="#" alt="Demo's logo" />
                        </div>
                    </div>
                    <div class="remi-footer-company-info">
                        © 2014–2019, DEMO
                        <br />
                        <span>All rights reserved.</span>
                        <br />
                        <span>Demo on stream</span>
                        <br />
                        <span>Website currency</span>
                    </div>
                </div>
                <div class="col-md-3 col-xs-12">
                    <h5 class="">Về chúng tôi</h5>
                    <ul>
                        <li><a href="#">Về Chúng Tôi</a></li>
                        <li><a href="#">Tuyển dụng</a></li>
                        <li><a href="#">Giao dịch đảm bảo</a></li>
                        <li><a href="#">Truyền thông</a></li>
                    </ul>
                </div>
                <div class="col-md-3 col-xs-12">
                    <h5 class="remi-footer-title">Liên hệ</h5>
                    <ul>
                        <li>
                            Email: <a href="#" target="_blank" rel="noopener noreferrer" class="remi-footer-email">mail@example.com</a>
                        </li>
                        <li>
                            <span class="remi-link">Hỗ trợ trực tuyến</span>
                        </li>
                        <li><a href="#" target="_blank" rel="noopener noreferrer">Liên hệ</a></li>
                        <li><a href="#" target="_blank" rel="noopener noreferrer">Blog</a></li>
                        <li>Số điện thoại gọi đi của chúng tôi là: +8888 888 888</li>
                    </ul><hr>
                </div>
                <div class="col-md-3 col-xs-12">
                    <h5 class="remi-footer-title">Mạng xã hội</h5>
                    <div class="row remi-footer-social">
                        <div class="col-xs-6">
                            <ul>
                                <li>
                                    <a target="_blank" rel="noopener noreferrer" to="https://www.facebook.com/" href="#">
                                        <div class="icon-facebook-squared svg-icon icon-white mr-8">
                                            @*<svg><use xlink:href="#facebook-squared"></use></svg>*@
                                        </div>
                                        <span>Facebook</span>
                                    </a>
                                </li>
                                <li>
                                    <a target="_blank" rel="noopener noreferrer" to="#" href="#">
                                        <div class="icon-twitter-squared svg-icon icon-white mr-8">
                                            @*<svg><use xlink:href="#twitter-squared"></use></svg>*@
                                        </div>
                                        <span>Twitter</span>
                                    </a>
                                </li>
                            </ul>
                        </div>
                        <div class="col-xs-6">
                            <ul>
                                <li>
                                    <a target="_blank" rel="noopener noreferrer" to="#" href="#">
                                        <div class="icon-linkedin-squared svg-icon icon-white mr-8">
                                            @*<svg><use xlink:href="#linkedin-squared"></use></svg>*@
                                        </div>
                                        <span>LinkedIn</span>
                                    </a>
                                </li>
                                <li>
                                    <a target="_blank" rel="noopener noreferrer" to="#" href="#">
                                        <div class="icon-telegram svg-icon icon-white mr-8">
                                            @*<svg><use xlink:href="#telegram"></use></svg>*@
                                        </div>
                                        <span>Telegram</span>
                                    </a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>

            </div>
        </footer>

    </div>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/myscripts/myjs")
    @RenderSection("scripts", required: false)
</body>
</html>