MoneyTransactions/MoneyTransactions.Web/Controllers/BankController.cs
using MoneyTransactions.BUS.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MoneyTransactions.WEB.Controllers
{
    public class BankController : Controller
    {
        private BankServices bankServices = new BankServices();
        private AccountService accountService = new AccountService();
        private WalletServices walletService = new WalletServices();
        /// <summary>
        /// Website for bank simulator        
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public ActionResult Details(int id)
        {
            return View();
        }

        [HttpGet]
        public ActionResult Login()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Login(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        [HttpGet]
        public ActionResult LogOut(int id)
        {
            return View();
        }

        [HttpGet]
        public ActionResult DepositFromBank(Guid accountID, string isType)
        {
            if (Session["AccountLogged"] == null)
            {
                return RedirectToAction("Login", "Home");
            }
            var getWall = walletService.FindWalletByAccountIdAndMoneyType(accountID, isType);
            if (getWall != null)
            {
                return View(getWall);
            }
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult DepositFromBank(FormCollection form)
        {
            if (Session["AccountLogged"] == null)
            {
                return RedirectToAction("Login", "Home");
            }

            // Guid accountID, string isType, string walletAddress, decimal luongTienNap
            if (form["diaChiVi"] != "")
            {
                var luongtienNap = decimal.Parse(form["luongTienNap"]);
                var findWallet = walletService.FindWalletByWalletAddress(form["diaChiVi"]);
                //var accInside = accountService.FindUserById(Guid.Parse(form["NapTienAccountID"]));
                var result = bankServices.NapTien(findWallet, luongtienNap);

                if (result)
                {
                    ViewBag.YourColorNapTien = "green";
                    ViewBag.NapTienResult = "Nạp tiền thành công";

                    return View("Close");
                }
            }

            ViewBag.YourColorNapTien = "red";
            ViewBag.NapTienResult = "Nạp tiền thất bại";

            return View("Close");
        }

        [HttpGet]
        public ActionResult WithdrawToBank(Guid accountID, string isType)
        {
            if (Session["AccountLogged"] == null)
            {
                return RedirectToAction("Login", "Home");
            }
            var getWall = walletService.FindWalletByAccountIdAndMoneyType(accountID, isType);
            if (getWall != null)
            {
                return View(getWall);
            }
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult WithdrawToBank(FormCollection form)
        {
            if (Session["AccountLogged"] == null)
            {
                return RedirectToAction("Login", "Home");
            }

            // Guid accountID, string isType, string walletAddress, decimal luongTienNap
            if (form["diaChiVi"] != "")
            {
                var luongtienNap = decimal.Parse(form["luongTienRut"]);
                var findWalletInside = walletService.FindWalletByWalletAddress(form["diaChiViInside"]);
                var findWalletOutside = walletService.FindWalletOutSideByAccountID(findWalletInside.Account.AccountID);

                var result = bankServices.RutTien(findWalletOutside, findWalletInside, luongtienNap, findWalletInside.CryptocurrencyStore.MoneyType);

                if (result)
                {
                    ViewBag.YourColorNapTien = "green";
                    ViewBag.NapTienResult = "Nạp tiền thành công";

                    return View("Close");
                }
            }

            ViewBag.YourColorNapTien = "red";
            ViewBag.NapTienResult = "Nạp tiền thất bại";
            return View("Close");
        }

        [HttpGet]
        public ActionResult Close()
        {
            return View();
        }
    }
}

MoneyTransactions/MoneyTransactions.Web/Controllers/HomeController.cs
using MoneyTransactions.BUS.Services;
using MoneyTransactions.Common;
using MoneyTransactions.Entities;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.RegularExpressions;
using System.Web;
using System.Web.Mvc;
using PagedList;
using System.Web.Script.Serialization;

namespace MoneyTransactions.WEB.Controllers
{
    public class HomeController : Controller
    {
        private readonly AccountService accountService = new AccountService();
        private OrderServices _orderServices = new OrderServices();
        private WalletServices _walletServices = new WalletServices();
        private readonly CryptocurrencyStoreServices cryptocurrencyStoreServices = new CryptocurrencyStoreServices();

        // GET: Home      
        [HttpGet]
        [AllowAnonymous]
        public ActionResult Index(int? pageSell, int? pageBuy)
        {
            if (pageSell != null)
            {
                int pageSize = 5;
                int pageIndex = 1;
                pageIndex = pageSell.HasValue ? Convert.ToInt32(pageSell) : 1;
                IPagedList<Order> o = null;

                o = _orderServices.ShowRecentTransaction().ToPagedList(pageIndex, pageSize);
                return View(o);
            }

            if (pageBuy != null)
            {
                int pageSize = 5;
                int pageIndex = 1;
                pageIndex = pageBuy.HasValue ? Convert.ToInt32(pageBuy) : 1;
                IPagedList<Order> o = null;

                o = _orderServices.ShowRecentTransaction().ToPagedList(pageIndex, pageSize);
                return View(o);
            }

            IPagedList<Order> i = _orderServices.ShowRecentTransaction().ToPagedList(1, 5);

            return View(i);
        }

        [HttpGet]
        public PartialViewResult ForSellIndex(int? pageSell)
        {
            int pageSize = 10;
            int pageIndex = 1;
            pageIndex = pageSell.HasValue ? Convert.ToInt32(pageSell) : 1;
            IPagedList<Order> o = null;

            o = _orderServices.ShowRecentTransaction().ToPagedList(pageIndex, pageSize);

            return PartialView(o);
        }

        [HttpGet]
        public PartialViewResult ForBuyIndex(int? pageBuy)
        {
            int pageSize = 10;
            int pageIndex = 1;
            pageIndex = pageBuy.HasValue ? Convert.ToInt32(pageBuy) : 1;
            IPagedList<Order> o = null;

            o = _orderServices.ShowRecentTransaction().ToPagedList(pageIndex, pageSize);

            return PartialView(o);
        }

        [HttpGet]
        public ActionResult UpdateMoney(string moneyType)
        {
            return Json(cryptocurrencyStoreServices.ShowFloorPrice(moneyType), JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public ActionResult FindWallet(string moneyType)
        {
            if (Session["AccountLogged"] != null)
            {
                var getUser = accountService.FindUserByUserName(Session["AccountLogged"].ToString());
                if (getUser != null)
                {
                    var WalletByTwoConditions = _walletServices.FindWalletByAccountIdAndMoneyType(getUser.AccountID, moneyType);
                    return Json(WalletByTwoConditions.WalletAddress, JsonRequestBehavior.AllowGet);
                }

            }

            return Json("", JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public ActionResult QuickTrade()
        {
            return View();
        }

        [HttpPost]
        public JsonResult GetListOrder(string amountSearch)
        {
            var regex = new Regex("^-?[0-9]*(\\.|\\,)?[0-9]+$");

            if (regex.IsMatch(amountSearch))
            {
                var changes = decimal.Parse(amountSearch);
                var changed = _orderServices.GetOrdersByAmount(changes);

                var json = "";
                json = JsonConvert.SerializeObject(changed);

                return Json(json, JsonRequestBehavior.AllowGet);
            }
            else
            {
                return Json("", JsonRequestBehavior.AllowGet);
            }
        }

        [HttpGet]
        public ActionResult MyProfile()
        {
            if (Session["AccountLogged"] == null)
            {
                return RedirectToAction("Login", "Account");
            }

            var getUser = accountService.FindUserByUserName(Session["AccountLogged"].ToString());
            if (getUser != null)
            {
                //var getWallet = _walletServices.FindWalletByAccountIdAndMoneyType(getUser.AccountID, CryptoCurrencyCommon.Bitcoin.ToString());
                //var getListWallet = _walletServices.ListWalletByAccountID(getUser.AccountID);

                //ViewBag.YourBTC = getListWallet.FirstOrDefault(b => b.CryptocurrencyStore.MoneyType.ToLower() == CryptoCurrencyCommon.Bitcoin.ToLower().ToString()).BalanceAmount;
                //ViewBag.YourETH = getListWallet.FirstOrDefault(b => b.CryptocurrencyStore.MoneyType.ToLower() == CryptoCurrencyCommon.Ethereum.ToLower().ToString()).BalanceAmount;
                //ViewBag.YourXRP = getListWallet.FirstOrDefault(b => b.CryptocurrencyStore.MoneyType.ToLower() == CryptoCurrencyCommon.Ripple.ToLower().ToString()).BalanceAmount;

                // Wallet Address
                //ViewBag.WalletAddressBTC = getListWallet.FirstOrDefault(b => b.CryptocurrencyStore.MoneyType.ToLower() == CryptoCurrencyCommon.Bitcoin.ToLower().ToString()).WalletAddress;
                //ViewBag.WalletAddressETH = getListWallet.FirstOrDefault(b => b.CryptocurrencyStore.MoneyType.ToLower() == CryptoCurrencyCommon.Ethereum.ToLower().ToString()).WalletAddress;                    
                //ViewBag.WalletAddressXRP = getListWallet.FirstOrDefault(b => b.CryptocurrencyStore.MoneyType.ToLower() == CryptoCurrencyCommon.Ripple.ToLower().ToString()).WalletAddress;

                // get username
                //ViewBag.UserName = getUser.UserName;
                //ViewBag.Email = getUser.Email;
                //ViewBag.Phone = getUser.Phone;
            }

            return View(getUser);
        }

        [HttpGet]
        public ActionResult Setting()
        {
            if (Session["AccountLogged"] == null)
            {
                return RedirectToAction("Login", "Account");
            }

            return View();
        }

        [HttpGet]
        public ActionResult YourWallet() // nap tien
        {
            if (Session["AccountLogged"] == null)
            {
                return RedirectToAction("Login", "Account");
            }

            var getUser = accountService.FindUserByUserName(Session["AccountLogged"].ToString());
            //ViewBag.yourBitcoin = getUser.Wallets.FirstOrDefault(b => b.CryptocurrencyStore.MoneyType == CryptoCurrencyCommon.Bitcoin).BalanceAmount;
            //ViewBag.yourVietNamDong = getUser.Wallets.FirstOrDefault(b => b.CryptocurrencyStore.MoneyType == CryptoCurrencyCommon.VietnamDong).BalanceAmount;
            //ViewBag.yourEthereum = getUser.Wallets.FirstOrDefault(b => b.CryptocurrencyStore.MoneyType == CryptoCurrencyCommon.Ethereum).BalanceAmount;
            //ViewBag.yourRipple = getUser.Wallets.FirstOrDefault(b => b.CryptocurrencyStore.MoneyType == CryptoCurrencyCommon.Ripple).BalanceAmount;

            return View(getUser);
        }

        [HttpGet]
        public ActionResult CommingSoon()
        {
            return View();
        }
    }
}

MoneyTransactions/MoneyTransactions.Web/Views/Home/CommingSoon.cshtml
@{
    ViewBag.Title = "Coming Soon";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<section class="page-heading remi-heading">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="title">
                    <strong style="color: white;">Coming soon</strong>
                </div>
            </div>
        </div>
    </div>
</section>


<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />

MoneyTransactions/MoneyTransactions.Web/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

MoneyTransactions/MoneyTransactions.Web/Views/Home/ForBuyIndex.cshtml
@using PagedList.Mvc
@model PagedList.IPagedList<MoneyTransactions.Entities.Order>



<!-- Ban muon mua bitcoin -->
<div class="sell-offers offer-list-section mb-24">
    <div class="title-accent heading-03">
        <div>
            <span style="font-size: 25px;">
                Bạn muốn <span class="text-success">mua</span> Bitcoin?
            </span>
        </div>
    </div>
</div>

<div class="render-body-bottom">
    <table class="table" style="border: none">
        @foreach (var item in Model)
        {
            if (item.OrderType == MoneyTransactions.Common.OrderCommon.OrderBuy)
            {
                <tbody>
                    <tr>
                        <th scope="row">@Html.DisplayFor(modelItem => item.Amount) BTC</th>
                        <td>@Html.DisplayFor(modelItem => item.Wallet.Account.UserName)</td>
                        <td>@Html.DisplayFor(modelItem => item.Wallet.CryptocurrencyStore.FloorPrice)</td>
                        <td> @Html.ActionLink("Mua", "Details", "Account", new { walletID = item.WalletID }, htmlAttributes: new { @class = "btn btn-info" })</td>
                    </tr>
                </tbody>
            }
        }
    </table>

    <div id="container" style="margin-left: 20px">
        <p></p>
        <p></p>
        <div class="pagination" style="margin-left: 400px">
            @*Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount   *@
            @Html.PagedListPager(Model, pageBuy => Url.Action("Index", new { pageBuy }), PagedListRenderOptions.ClassicPlusFirstAndLast)
        </div>
    </div>


    <div class="container-fluid">
        <div class="row-with-thick-left-border row flex-row remi-want-better-price px-24 py-16">
            <div class="col-xs-12s px-0 mb-4">
                <span>
                    Muốn giá tốt hơn?
                </span>
            </div>
            <div class="col-xs-12s px-0">
                @Html.ActionLink("Tạo quảng cáo mua", "CreateBuyAd", "Account", new { getMoneyType = "bitcoin" }, new { @class = "btn btn-success" })
            </div>
        </div>
    </div>

</div>

MoneyTransactions/MoneyTransactions.Web/Views/Home/ForSellIndex.cshtml
@using PagedList.Mvc
@model PagedList.IPagedList<MoneyTransactions.Entities.Order>


<!-- Danh muc ban -->
<!-- Ban muon mua bitcoin -->
<div class="sell-offers offer-list-section mb-24">
    <div class="title-accent heading-03">
        <div>
            <span style="font-size: 25px;">
                Bạn muốn <span class="text-danger">bán</span> Bitcoin?
            </span>
        </div>
    </div>
</div>

<div class="render-body-bottom">
    <table class="table" style="border: none">
        @foreach (var item in Model)
        {
            if (item.OrderType == MoneyTransactions.Common.OrderCommon.OrderSell)
            {
                <tbody>
                    <tr>
                        <th scope="row">@Html.DisplayFor(modelItem => item.Amount) BTC</th>
                        <td>@Html.DisplayFor(modelItem => item.Wallet.Account.UserName)</td>
                        <td>@Html.DisplayFor(modelItem => item.Wallet.CryptocurrencyStore.FloorPrice)</td>
                        <td> @Html.ActionLink("Bán", "Details", "Account", new { walletID = item.WalletID }, htmlAttributes: new { @class = "btn btn-info" })</td>
                    </tr>
                </tbody>
            }
        }
    </table>

    <div id="container" style="margin-left: 20px">
        <p></p>
        <p></p>
        <div class="pagination" style="margin-left: 400px">
            @*Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount *@
            @Html.PagedListPager(Model, pageSell => Url.Action("Index", new { pageSell }), PagedListRenderOptions.ClassicPlusFirstAndLast)
        </div>
    </div>

    <div class="container-fluid">
        <div class="row-with-thick-left-border row flex-row remi-want-better-price px-24 py-16">
            <div class="col-xs-12s px-0 mb-4">
                <span>
                    Muốn giá tốt hơn?
                </span>
            </div>
            <div class="col-xs-12s px-0">
                @Html.ActionLink("Tạo quảng cáo bán", "CreateSellAd", "Account", new { getMoneyType = "bitcoin" }, new { @class = "btn btn-danger" })
            </div>
        </div>
    </div>
</div>

MoneyTransactions/MoneyTransactions.Web/Views/Home/PartialViewResult.cshtml
<div class="navbar-collapse collapse">
    <ul class="nav navbar-nav remi-header-top-menu">
        <li>@Html.ActionLink("Example 1", "Index", "Home")</li>
        <li>@Html.ActionLink("Example 2", "About", "Home")</li>
        <li>@Html.ActionLink("Example 3", "Contact", "Home")</li>
        <li>@Html.ActionLink("Đăng nhập / Đăng ký", "Login", "Account")</li>
    </ul>
</div>

MoneyTransactions/MoneyTransactions.Web/Views/Home/QuickTrade.cshtml
@{
    ViewBag.Title = "Giao dịch nhanh";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<section class="page-heading remi-heading">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="title">
                    <strong style="color: white;">Giao dịch nhanh</strong>
                </div>
            </div>
        </div>
    </div>
</section>

@*<link href="//netdna.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//netdna.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
    <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>*@
<!------ Include the above in your HEAD tag ---------->

<div class="container">
    <br />
    <br />

    <div class="row">
        <div class="panel with-nav-tabs panel-default">
            <div class="panel-heading">
                <ul class="nav nav-tabs">
                    <li class="active"><a href="#tab1default" data-toggle="tab">Mua ngay</a></li>
                    <li><a href="#tab2default" data-toggle="tab">Bán ngay</a></li>
                </ul>
            </div>

            <div class="panel-body">
                <div class="tab-content">
                    <div class="tab-pane fade in active" id="tab1default">

                        <div class="row">
                            <div class="col-sm-6">
                                Nhập số lượng:
                                <input type="text" id="soLuongMoney" name="" onkeyup="UserInputQuicktrade();" value="" class="form-control" />
                                <div></div>  <!-- Danh cho message -->
                            </div>
                            <div class="col-sm-6">
                                Địa chỉ ví của bạn
                                <input type="text" id="" name="soluong" value="" class="form-control" />
                            </div>
                        </div>

                        <br />
                        <br />

                        <!-- Handle Mua tu -->
                        <div>
                            <h2 style="font-weight: bold;">Mua từ</h2>
                            <div id="showPageForMuaTu">
                                @*
                                <div style="margin-bottom: 5px;">
                                    <div class="row" style="background-color:#e6e6e6;padding-top: 25px; margin: 0 auto;">
                                        <div class="col-sm-10">
                                            <p>Tài khoản: </p>
                                            <p>Số lượng: </p>
                                            <p>Tỉ giá: </p>
                                        </div>
                                        <div class="col-sm-2">
                                            <!-- A link here -->
                                            <a href="#" class="btn btn-ask">Mua ngay</a>
                                        </div>
                                    </div>
                                </div>

                                <div style="margin-bottom: 5px;">
                                    <div class="row" style="background-color:#e6e6e6;padding-top: 25px; margin: 0 auto;">
                                        <div class="col-sm-10">
                                            <p>Tài khoản: </p>
                                            <p>Số lượng: </p>
                                            <p>Tỉ giá: </p>
                                        </div>
                                        <div class="col-sm-2">
                                            <!--A link here-->
                                            <a href="#" class="btn btn-ask">Mua ngay</a>
                                        </div>
                                    </div>
                                </div>
                            *@
                            </div>
                        </div>
                        <!-- Handle Mua tu -->


                    </div>
                    <div class="tab-pane fade" id="tab2default">

                        <div class="row">
                            <div class="col-sm-6">
                                Nhập số lượng:
                                <input type="text" id="soLuongMoneySellFor" name="soluong" value="" onkeyup="UserInputQuicktradeForSell()" class="form-control" />
                                <div></div> <!-- Danh cho message -->
                            </div>
                            <div class="col-sm-6">
                                Địa chỉ ví của bạn
                                <input type="text" name="soluong" value="" class="form-control" />
                            </div>
                        </div>

                        <br />
                        <br />

                        <!-- Handle Ban cho -->
                        <div>
                            <h2 style="font-weight: bold;">Bán cho</h2>
                            <div id="showforSellFor"></div>
                        </div>
                        <!-- Handle Ban cho -->

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>






<!-- Br -->
<div>

    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />

</div>

MoneyTransactions/MoneyTransactions.Web/Views/Home/YourWallet.cshtml
@model MoneyTransactions.Entities.Account

@{
    ViewBag.Title = "Your Wallet";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<section class="page-heading remi-heading">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="title">
                    <strong style="color: white;">Ví tiền</strong>
                </div>
            </div>
        </div>
    </div>
</section>



<div class="main">
    <section class="container profile">
        <br>
        <div class="row">
            <div class="col-md-6">
                <div class="loading-container text-center">
                    <div class="loading-bar"></div>
                </div>
                <div class="panel panel-default profile-details">
                    <table class="table table-striped">
                        <tbody>

                            @foreach (var item in Model.Wallets)
                            {
                                <!-- Ripple -->
                                <tr>
                                    <td>
                                        @{
                                            if (@item.CryptocurrencyStore.MoneyType == MoneyTransactions.Common.CryptoCurrencyCommon.Bitcoin)
                                            {
                                                <text>
                                                    Bitcoin(BTC)
                                                </text>
                                            }
                                            if (@item.CryptocurrencyStore.MoneyType == MoneyTransactions.Common.CryptoCurrencyCommon.Ethereum)
                                            {
                                                <text>
                                                    Ethereum(ETH)
                                                </text>
                                            }
                                            if (@item.CryptocurrencyStore.MoneyType == MoneyTransactions.Common.CryptoCurrencyCommon.Ripple)
                                            {
                                                <text>
                                                    Ripple(XRP)
                                                </text>
                                            }
                                            if (@item.CryptocurrencyStore.MoneyType == MoneyTransactions.Common.CryptoCurrencyCommon.VietnamDong)
                                            {
                                                <text>
                                                    Việt Nam Đồng(VNĐ)
                                                </text>
                                            }
                                        }

                                    </td>
                                    <td>
                                        @item.BalanceAmount
                                    </td>
                                    <td>
                                        @Html.ActionLink("Nạp tiền", "DepositFromBank", "Bank", new { accountID = @item.AccountID, isType = @item.CryptocurrencyStore.MoneyType }, new { @class = "btn btn-success", @target = "_blank" })
                                    </td>
                                    <td>
                                        @Html.ActionLink("Rút tiền", "WithdrawToBank", "Bank", new { accountID = @item.AccountID, isType = @item.CryptocurrencyStore.MoneyType }, new { @class = "btn btn-danger", @target = "_blank" })
                                    </td>
                                </tr>
                            }


                        </tbody>
                    </table>
                </div>
            </div>

            <div class="col-md-6" hidden>
                <div class="feedback-contents text-center">
                    <div class="feedback-title title-accent">
                        <h3><span>Phản hồi về bluebox</span></h3>
                    </div>
                    <div class="loading-container text-center">
                        <div class="loading-bar"></div>
                    </div>
                    <div class="empty-feedbacks">
                        <i>Không có phản hồi</i>
                        <p></p>
                    </div>
                </div>
            </div>
        </div>

        <div class="row profile-offers my-16" hidden>
            <div class="col-xs-12">
                <div class="sell-offers offer-list-section mb-24">
                    <div class="title-accent heading-03">
                        <span>
                            <span class="vertical-middless">Mua từ @Model.UserName</span>
                        </span>
                    </div>
                    <div class="loading-container text-center">
                        <div class="loading-bar"></div>
                    </div>
                    <div class="content-wrapper mt-16">
                        <div class="main-container container-fluid">
                            <div class="row no-offers pt-0 pb-16 px-16">
                                <div class="col-xs-12"><i></i></div>
                            </div>
                        </div>
                    </div>
                </div>
                <hr>
                <div class="buy-offers offer-list-section mb-24">
                    <div class="title-accent heading-03">
                        <span>
                            <span class="vertical-middless">Bán cho @Model.UserName</span>
                        </span>
                    </div>
                    <div class="loading-container text-center">
                        <div class="loading-bar"></div>
                    </div>
                    <div class="content-wrapper mt-16">
                        <div class="main-container container-fluid">
                            <div class="row no-offers pt-0 pb-16 px-16">
                                <div class="col-xs-12"><i></i></div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
</div>

<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />